# Dockerfile.rust
FROM rust:1.85-alpine3.20

WORKDIR /app

# Copiar os arquivos de manifesto primeiro para aproveitar o cache de construção
COPY flood_fill_rust/Cargo.toml .
COPY flood_fill_rust/Cargo.lock .

# Criar diretório src e copiar os arquivos fonte
RUN mkdir src
COPY flood_fill_rust/src/ ./src/

# Compilar e executar os testes
CMD ["cargo", "test", "--", "--nocapture"]